# smoke178 - #178 undo-delete (Ctrl+Z / Edit -> Undo Delete, command id
# 122) GUI smoke matrix. ASCII-only source (PS 5.1 ANSI/param-binding
# trap, #79 lesson). Harness cribbed from smoke165/smoke173: poll-based
# waits everywhere (posted-message latency is unbounded), path-targeted
# process handling, GetExitCodeProcess on the handle captured WHILE
# ALIVE, the owned-dialog ladder (EnumWindows filtered by pid + class
# #32770), and the C# chunk/zlib PNG writer (8x8 solid fixtures, three
# distinct colors, mtimes staged c -> b -> a with 1.1s gaps so the
# default DateModified-descending nav order is a, b, c).
#
# Command ids (src/menu.rs, unit-tested there): FileDeleteRecycle=13,
# FileDeletePermanently=14, NavNext=107, NavPrev=108, EditUndoDelete=122.
# Both delete commands surface the SHELL's own confirm dialog (class
# #32770; the Yes button carries control id IDYES = 6). Undo semantics
# (src/window.rs undo_delete_current / delete_current, src/filemgmt.rs
# recycle_restore): depth 1 (only the most recent recycle delete);
# permanent delete retires the record; a consumed record makes 122 a
# no-op; a restore blocked by a squatter at the target path is refused
# and KEEPS the record for a retry.
#
# Title contract (src/text.rs): "<path or filename> - riviv"; a blanked
# display carries the app name only ("riviv"). All title assertions are
# substring matches (Wait-TitleHas / Wait-TitleLacks).
#
# The exe runs FROM target\release (task discipline #2): the run BLOCKS
# when target\release\riviv.ini already exists (possibly user data -
# never deleted by this script), and the ini generated BY THIS RUN is
# deleted at the end. No SHEmptyRecycleBin anywhere (never touches the
# real bin globally); fixture files sent to the recycle bin are tracked
# and any outstanding residue is reported at the end.
#
# Scenarios (launch 1 = playlist arm a,b,c; launch 2 = direct open a):
#   S1  id 13 + shell Yes: a.png recycled (gone from disk), title b.png
#   S2  id 122: a.png back byte-identical, title a.png; NavNext ->
#       b.png; NavPrev -> a.png (re-insert position and order intact)
#   S3  id 122 again (record consumed): no-op - title stays a.png,
#       files intact, process alive
#   S4  NavNext x2 -> c.png; id 14 + Yes: c.png gone for good, title
#       wraps to a.png; id 122 does NOT bring c.png back
#   S5  NavNext -> b.png; id 13 + Yes: b.png recycled; squatter new
#       b.png bytes + id 122: restore refused (new bytes intact, title
#       stays a.png); squatter removed + id 122 retry: ORIGINAL b.png
#       bytes back, title b.png
#   S6  (launch 2) id 122 right after the direct-open adopt: no-op -
#       title unchanged, a.png intact, process alive
#   S7  WM_INITMENU -> GetMenuState(122) is MF_GRAYED; id 13 + Yes ->
#       a.png gone, title blanks to the app name only (launch 2 runs with
#       fx holding ONLY a.png - the playlist-less nav does a live folder
#       scan, so leftovers would hijack the delete's nav target);
#       WM_INITMENU -> 122 enabled; id 122 -> a.png restored
#       byte-identical, title a.png
#
# Output contract: one line per scenario ("S<n>: PASS/FAIL <evidence>"),
# final line "SMOKE178: <pass>/<total>". Exit codes: 0 all pass,
# 1 failures, 2 missing exe, 4 BLOCKED (pre-existing ini / foreign
# riviv process).

param([string]$Exe = 'D:\codespace\riviv\target\release\riviv.exe')

$ErrorActionPreference = 'Stop'

Add-Type -TypeDefinition @'
using System;
using System.Collections.Generic;
using System.IO;
using System.IO.Compression;
using System.Text;
using System.Runtime.InteropServices;

public class S178 {
    [DllImport("user32.dll")] public static extern bool SetProcessDPIAware();
    [DllImport("user32.dll")] public static extern bool PostMessage(IntPtr hwnd, uint msg, IntPtr wp, IntPtr lp);
    [DllImport("user32.dll", CharSet=CharSet.Unicode)] public static extern int GetWindowText(IntPtr hwnd, StringBuilder sb, int max);
    [DllImport("user32.dll")] public static extern bool IsWindow(IntPtr h);
    [DllImport("user32.dll")] public static extern IntPtr GetDlgItem(IntPtr dlg, int id);
    [DllImport("user32.dll")] public static extern int GetDlgCtrlID(IntPtr hwnd);
    [DllImport("user32.dll")] public static extern IntPtr GetMenu(IntPtr hwnd);
    [DllImport("user32.dll")] public static extern uint GetMenuState(IntPtr hMenu, uint uId, uint uFlags);
    [DllImport("kernel32.dll")] public static extern bool GetExitCodeProcess(IntPtr h, out int code);

    public delegate bool EnumProc(IntPtr hwnd, IntPtr lparam);
    [DllImport("user32.dll", CharSet=CharSet.Unicode)] public static extern bool EnumWindows(EnumProc cb, IntPtr lparam);
    [DllImport("user32.dll", CharSet=CharSet.Unicode)] public static extern bool EnumChildWindows(IntPtr hwnd, EnumProc cb, IntPtr lparam);
    [DllImport("user32.dll")] public static extern uint GetWindowThreadProcessId(IntPtr hwnd, out uint pid);
    [DllImport("user32.dll", CharSet=CharSet.Unicode)] public static extern int GetClassName(IntPtr hwnd, StringBuilder sb, int max);

    public static string TitleOf(IntPtr hwnd) {
        StringBuilder sb = new StringBuilder(512);
        GetWindowText(hwnd, sb, 512);
        return sb.ToString();
    }

    // Diagnostics for an unexpected dialog shape: every descendant as
    // "class:controlid" so a ladder miss can be attributed honestly.
    public static string ChildrenDump(IntPtr dlg) {
        List<string> parts = new List<string>();
        EnumProc cb = delegate(IntPtr h, IntPtr lp) {
            StringBuilder sb = new StringBuilder(256);
            GetClassName(h, sb, 256);
            parts.Add(sb.ToString() + ":" + GetDlgCtrlID(h).ToString());
            return true;
        };
        EnumChildWindows(dlg, cb, IntPtr.Zero);
        return string.Join(" | ", parts.ToArray());
    }

    // ---- PNG fixture writing (smoke165/smoke173's verified recipe) ----
    static void PutBe32(byte[] b, int o, uint v) {
        b[o] = (byte)(v >> 24); b[o+1] = (byte)(v >> 16); b[o+2] = (byte)(v >> 8); b[o+3] = (byte)v;
    }
    static uint Crc32(byte[] data) {
        uint c = 0xFFFFFFFF;
        foreach (byte x in data) { c ^= x; for (int k = 0; k < 8; k++) c = ((c & 1) != 0) ? (0xEDB88320 ^ (c >> 1)) : (c >> 1); }
        return c ^ 0xFFFFFFFF;
    }
    static void Chunk(MemoryStream ms, string type, byte[] data) {
        byte[] len = new byte[4]; PutBe32(len, 0, (uint)data.Length);
        ms.Write(len, 0, 4);
        byte[] tb = Encoding.ASCII.GetBytes(type);
        ms.Write(tb, 0, 4);
        ms.Write(data, 0, data.Length);
        byte[] crcIn = new byte[data.Length + 4];
        tb.CopyTo(crcIn, 0); data.CopyTo(crcIn, 4);
        byte[] crc = new byte[4]; PutBe32(crc, 0, Crc32(crcIn));
        ms.Write(crc, 0, 4);
    }
    static byte[] Zlib(byte[] raw) {
        MemoryStream comp = new MemoryStream();
        comp.WriteByte(0x78); comp.WriteByte(0x01);
        DeflateStream ds = new DeflateStream(comp, CompressionLevel.Fastest, true);
        ds.Write(raw, 0, raw.Length);
        ds.Close();
        uint a1 = 1, a2 = 0;
        for (int i = 0; i < raw.Length; i++) { a1 = (a1 + raw[i]) % 65521; a2 = (a2 + a1) % 65521; }
        uint adler = (a2 << 16) | a1;
        comp.WriteByte((byte)(adler >> 24)); comp.WriteByte((byte)(adler >> 16));
        comp.WriteByte((byte)(adler >> 8)); comp.WriteByte((byte)adler);
        return comp.ToArray();
    }
    static byte[] Scanlines(int w, int h, byte[] rgba) {
        byte[] raw = new byte[h * (1 + w * 4)];
        for (int y = 0; y < h; y++) {
            raw[y * (1 + w * 4)] = 0; // filter: none
            Array.Copy(rgba, y * w * 4, raw, y * (1 + w * 4) + 1, w * 4);
        }
        return raw;
    }
    // An 8x8 RGBA8 solid PNG with NO ancillary chunks.
    public static void WritePng8(string path, byte r, byte g, byte b) {
        int w = 8, h = 8;
        byte[] px = new byte[w * h * 4];
        for (int i = 0; i < w * h; i++) { px[i*4] = r; px[i*4+1] = g; px[i*4+2] = b; px[i*4+3] = 255; }
        MemoryStream ms = new MemoryStream();
        byte[] sig = { 0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A };
        ms.Write(sig, 0, 8);
        byte[] ihdr = new byte[13];
        PutBe32(ihdr, 0, (uint)w); PutBe32(ihdr, 4, (uint)h);
        ihdr[8] = 8; ihdr[9] = 6; // RGBA8
        Chunk(ms, "IHDR", ihdr);
        Chunk(ms, "IDAT", Zlib(Scanlines(w, h, px)));
        Chunk(ms, "IEND", new byte[0]);
        File.WriteAllBytes(path, ms.ToArray());
    }
}
'@

# ---------------------------------------------------------------------------
# Stage paths. Logs and intermediates live in %TEMP%\riviv-178-smoke\; the
# fixtures live in fx\ underneath it. The exe runs from target\release per
# the task discipline, so the ini discipline targets target\release.
# ---------------------------------------------------------------------------
$Stage = Join-Path $env:TEMP 'riviv-178-smoke'
$Fx = Join-Path $Stage 'fx'
$Afx = Join-Path $Fx 'a.png'
$Bfx = Join-Path $Fx 'b.png'
$Cfx = Join-Path $Fx 'c.png'
$Ini = 'D:\codespace\riviv\target\release\riviv.ini'
$LogPath = Join-Path $Stage 'smoke178-run1.log'

# ---------------------------------------------------------------------------
# BLOCKED gates - BEFORE anything else, per task discipline.
# ---------------------------------------------------------------------------
if (-not (Test-Path $Exe)) { Write-Output ('MISSING EXE: ' + $Exe); exit 2 }
if (Test-Path $Ini) {
    Write-Output ('BLOCKED: ' + $Ini + ' already exists (possibly user data). Delete it yourself (or move it) and rerun; this script will not touch it.')
    exit 4
}
$preExisting = @(Get-Process riviv -ErrorAction SilentlyContinue)
if ($preExisting.Count -gt 0) {
    $fxPids = ($preExisting | ForEach-Object { $_.Id }) -join ','
    Write-Output ('BLOCKED: riviv.exe already running (not spawned by this script) - close it and rerun (pids: ' + $fxPids + ').')
    exit 4
}

if (-not (Test-Path $Stage)) { New-Item -ItemType Directory -Path $Stage | Out-Null }
Get-ChildItem -LiteralPath $Stage -Force |
    Where-Object { $_.Name -notlike 'smoke178-run*.log' } |
    Remove-Item -Recurse -Force -ErrorAction SilentlyContinue
if (Test-Path $Fx) { Remove-Item $Fx -Recurse -Force -ErrorAction SilentlyContinue }
New-Item -ItemType Directory -Path $Fx | Out-Null

$script:logOpen = $false
try {
    Start-Transcript -Path $LogPath | Out-Null
    $script:logOpen = $true
} catch {
    Write-Host ('WARN transcript failed, continuing without tee: ' + $_.Exception.Message)
}
function Stop-Log {
    if ($script:logOpen) {
        try { Stop-Transcript | Out-Null } catch { }
        $script:logOpen = $false
    }
}

# ---------------------------------------------------------------------------
# Harness
# ---------------------------------------------------------------------------
$script:pass = 0
$script:fail = 0
$script:total = 0
function Emit-S($id, $ok, $ev) {
    $script:total++
    $v = 'FAIL'
    if ($ok) { $v = 'PASS'; $script:pass++ } else { $script:fail++ }
    Write-Output ($id + ': ' + $v + ' ' + $ev)
}
function Det($tag, $ok, $text) {
    $v = 'FAIL'
    if ($ok) { $v = 'PASS' }
    Write-Host ('  [' + $tag + '] ' + $v + ' ' + $text)
}
function Wait-Until($sb, $ms) {
    $deadline = [DateTime]::UtcNow.AddMilliseconds($ms)
    while ([DateTime]::UtcNow -lt $deadline) {
        if (& $sb) { return $true }
        Start-Sleep -Milliseconds 100
    }
    return (& $sb)
}
function Start-Riv($argStr, $errName) {
    $errPath = Join-Path $Stage $errName
    if (Test-Path $errPath) { Remove-Item $errPath -Force }
    $p = Start-Process -FilePath $Exe -ArgumentList $argStr -PassThru -RedirectStandardError $errPath
    $p.Handle | Out-Null   # capture the handle WHILE ALIVE (smoke80 lesson)
    return $p
}
function Wait-Main($p) {
    for ($i = 0; $i -lt 150; $i++) {
        Start-Sleep -Milliseconds 100
        $p.Refresh()
        $h = $p.MainWindowHandle
        if (($h -ne $null) -and ($h -ne [IntPtr]::Zero)) { return $h }
        if ($p.HasExited) { break }
    }
    return [IntPtr]::Zero
}
function Get-Title($main) {
    if (($main -eq $null) -or ($main -eq [IntPtr]::Zero)) { return '(no main window)' }
    return [S178]::TitleOf($main)
}
function Wait-TitleHas($main, $leaf, $ms) {
    $deadline = [DateTime]::UtcNow.AddMilliseconds($ms)
    while ([DateTime]::UtcNow -lt $deadline) {
        if ((Get-Title $main).Contains($leaf)) { return $true }
        Start-Sleep -Milliseconds 100
    }
    return (Get-Title $main).Contains($leaf)
}
function Wait-TitleLacks($main, $leaf, $ms) {
    # The negative waits are real polls too: a WRONG title change must be
    # caught if it happens inside the window, not missed by an instant check.
    # Returns $true only when the title never gains the leaf within $ms.
    $deadline = [DateTime]::UtcNow.AddMilliseconds($ms)
    while ([DateTime]::UtcNow -lt $deadline) {
        if ((Get-Title $main).Contains($leaf)) { return $false }
        Start-Sleep -Milliseconds 100
    }
    return -not (Get-Title $main).Contains($leaf)
}
function Post-Cmd($main, $id) {
    # WM_COMMAND(wParam = command id, lParam = 0) to the owner main window.
    [void][S178]::PostMessage($main, 0x0111, [IntPtr]$id, [IntPtr]::Zero)
}
function Wait-Exit($p, $ms) {
    # Exit code via GetExitCodeProcess on the handle captured while alive.
    if ($p.WaitForExit($ms)) {
        $code = 0
        [void][S178]::GetExitCodeProcess($p.Handle, [ref]$code)
        return $code
    }
    return $null
}
function Hash-Of($path) {
    # Shared-read hash (riviv may still hold the file when polled).
    for ($i = 0; $i -lt 10; $i++) {
        try {
            if (-not (Test-Path $path)) { return '(absent)' }
            $fs = [IO.File]::Open($path, [IO.FileMode]::Open, [IO.FileAccess]::Read, [IO.FileShare]::ReadWrite)
            try {
                $sha = [System.Security.Cryptography.SHA256]::Create()
                $h = $sha.ComputeHash($fs)
                return ([BitConverter]::ToString($h)).Replace('-', '').ToLower()
            } finally { $fs.Dispose() }
        } catch { Start-Sleep -Milliseconds 100 }
    }
    return '(unreadable)'
}
function Wait-FileState($path, $wantExists, $ms) {
    $deadline = [DateTime]::UtcNow.AddMilliseconds($ms)
    while ([DateTime]::UtcNow -lt $deadline) {
        if ((Test-Path $path) -eq $wantExists) { return $true }
        Start-Sleep -Milliseconds 100
    }
    return ((Test-Path $path) -eq $wantExists)
}

# ---- window/dialog helpers -------------------------------------------------
function Get-Class($h) {
    $sb = New-Object System.Text.StringBuilder 256
    [void][S178]::GetClassName($h, $sb, 256)
    return $sb.ToString()
}
function Find-OwnDialogs($procId) {
    # All top-level #32770 windows of OUR process (FindWindowW alone could
    # hit another process's dialog, so enumerate and filter by pid).
    $script:topHits = @()
    $cb = [S178+EnumProc]{ param($h, $lp) $script:topHits += $h; return $true }
    [void][S178]::EnumWindows($cb, [IntPtr]::Zero)
    $found = @()
    foreach ($h in $script:topHits) {
        if ((Get-Class $h) -eq '#32770') {
            $wpid = 0
            [void][S178]::GetWindowThreadProcessId($h, [ref]$wpid)
            if ($wpid -eq $procId) { $found += $h }
        }
    }
    $script:topHits = $null
    return ,$found
}
function Wait-DialogGone($dlg, $ms) {
    $deadline = [DateTime]::UtcNow.AddMilliseconds($ms)
    while ([DateTime]::UtcNow -lt $deadline) {
        if (-not [S178]::IsWindow($dlg)) { return $true }
        Start-Sleep -Milliseconds 100
    }
    return (-not [S178]::IsWindow($dlg))
}
function Invoke-ConfirmYes($procId, $gonePath, $ms) {
    # The delete-confirm ladder: poll for a #32770 of our pid that carries a
    # Yes button (GetDlgItem id 6 = IDYES), BM_CLICK it, wait for the dialog
    # to go. If no dialog ever appears but the target file vanishes anyway,
    # classify as AutoNoDialog (delete confirmations disabled on this
    # machine) instead of burning the full $ms. Unexpected shapes get a
    # child-control dump for honest attribution.
    $dlg = [IntPtr]::Zero
    $anyDlg = [IntPtr]::Zero
    $deadline = [DateTime]::UtcNow.AddMilliseconds($ms)
    while ([DateTime]::UtcNow -lt $deadline) {
        foreach ($d in (Find-OwnDialogs $procId)) {
            if ($anyDlg -eq [IntPtr]::Zero) { $anyDlg = $d }
            if ([S178]::GetDlgItem($d, 6) -ne [IntPtr]::Zero) { $dlg = $d; break }
        }
        if ($dlg -ne [IntPtr]::Zero) { break }
        if (-not (Test-Path $gonePath)) { break }
        Start-Sleep -Milliseconds 100
    }
    $res = @{ Dlg = $dlg; YesClicked = $false; Gone = $false; AutoNoDialog = $false; AnyDlg = $anyDlg; Children = '' }
    if ($dlg -ne [IntPtr]::Zero) {
        $yes = [S178]::GetDlgItem($dlg, 6)
        [void][S178]::PostMessage($yes, 0x00F5, [IntPtr]::Zero, [IntPtr]::Zero)   # BM_CLICK
        $res.YesClicked = $true
        if (Wait-DialogGone $dlg 6000) {
            $res.Gone = $true
        } else {
            Write-Host '  [dialog] first BM_CLICK on Yes did not dismiss it, retrying once'
            [void][S178]::PostMessage($yes, 0x00F5, [IntPtr]::Zero, [IntPtr]::Zero)
            if (Wait-DialogGone $dlg 4000) { $res.Gone = $true }
            else { $res.Children = [S178]::ChildrenDump($dlg) }
        }
    } else {
        if ($anyDlg -ne [IntPtr]::Zero) { $res.Children = [S178]::ChildrenDump($anyDlg) }
        if (Test-Path $gonePath) { } else { $res.AutoNoDialog = $true }
    }
    return $res
}
function Menu-State122($main) {
    # PostMessage WM_INITMENU (the app refreshes its BAR menu on it -
    # src/window.rs on_initmenu over GetMenu(hwnd), the wParam is ignored),
    # then read command 122's state MF_BYCOMMAND. 0xFFFFFFFF = no menu or
    # item absent. Each poll re-posts the (idempotent) refresh.
    [void][S178]::PostMessage($main, 0x0116, [IntPtr]::Zero, [IntPtr]::Zero)   # WM_INITMENU
    Start-Sleep -Milliseconds 200
    $bar = [S178]::GetMenu($main)
    if ($bar -eq [IntPtr]::Zero) { return [uint32]4294967295 }
    return [S178]::GetMenuState($bar, [uint32]122, [uint32]0)
}
function Wait-Menu122Grayed($main, $ms) {
    $ok = Wait-Until { $s = Menu-State122 $main; (($s -ne [uint32]4294967295) -and (($s -band [uint32]1) -ne 0)) } $ms
    return @{ Ok = $ok; State = (Menu-State122 $main) }
}
function Wait-Menu122Enabled($main, $ms) {
    $ok = Wait-Until { $s = Menu-State122 $main; (($s -ne [uint32]4294967295) -and (($s -band [uint32]1) -eq 0)) } $ms
    return @{ Ok = $ok; State = (Menu-State122 $main) }
}

[void][S178]::SetProcessDPIAware()

# ---------------------------------------------------------------------------
# Fixtures: 8x8 solid PNGs, three distinct colors, mtimes staged
# c -> (1.1s) -> b -> (1.1s) -> a so DateModified-descending nav order is
# a, b, c. Original byte hashes recorded for the byte-identity assertions.
# ---------------------------------------------------------------------------
[S178]::WritePng8($Cfx, 30, 30, 220)    # blue
Start-Sleep -Milliseconds 1100
[S178]::WritePng8($Bfx, 30, 220, 30)    # green
Start-Sleep -Milliseconds 1100
[S178]::WritePng8($Afx, 220, 30, 30)    # red
$ma = (Get-Item $Afx).LastWriteTimeUtc
$mb = (Get-Item $Bfx).LastWriteTimeUtc
$mc = (Get-Item $Cfx).LastWriteTimeUtc
$hA0 = Hash-Of $Afx
$hB0 = Hash-Of $Bfx
$hC0 = Hash-Of $Cfx
$fixtureOk = ($ma -gt $mb) -and ($mb -gt $mc) -and
    (($hA0 -ne $hB0) -and ($hB0 -ne $hC0) -and ($hA0 -ne $hC0))
Write-Host ('  [fixtures] ok=' + $fixtureOk + ' mtimes a>b,c: ' + $ma.ToString('HH:mm:ss.fff') + ' / ' + $mb.ToString('HH:mm:ss.fff') + ' / ' + $mc.ToString('HH:mm:ss.fff'))
Write-Host ('  [fixtures] sha256 a=' + $hA0 + ' b=' + $hB0 + ' c=' + $hC0)
if (-not $fixtureOk) {
    Write-Output 'FIXTURES: FAIL - mtime order or byte distinctness broken; matrix aborted.'
    Stop-Log
    exit 1
}

# Fixture files that currently sit in the recycle bin (outstanding residue
# tracker; nothing here ever calls SHEmptyRecycleBin).
$script:binOutstanding = New-Object System.Collections.Generic.List[string]

$u32max = [uint32]4294967295
$exitNote1 = ''
$exitNote2 = ''

try {

# ===========================================================================
# LAUNCH 1 (playlist arm): a.png b.png c.png -> playlist, current = a.
# ===========================================================================
$p1 = Start-Riv ('"' + $Afx + '" "' + $Bfx + '" "' + $Cfx + '"') 'launch1.err'
$main1 = Wait-Main $p1
$adopt1 = Wait-TitleHas $main1 'a.png' 15000
Start-Sleep -Milliseconds 800   # settle
$alive1 = (-not $p1.HasExited)
Write-Host ('  [launch1] pid=' + $p1.Id + ' main=' + $main1 + ' adopted=' + $adopt1 + ' title=[' + (Get-Title $main1) + ']')

# ---------------------------------------------------------------------------
# S1: WM_COMMAND 13 -> shell confirm dialog -> Yes. a.png recycled off disk,
# nav lands on b.png.
# ---------------------------------------------------------------------------
$ok1 = $alive1 -and $adopt1
$ev1 = ''
if (-not $ok1) { $ev1 = 'launch1 adopt failed: alive=' + $alive1 + ' adopted=' + $adopt1 + ' title=[' + (Get-Title $main1) + ']' }
$d1 = $null
if ($ok1) {
    Post-Cmd $main1 13
    $d1 = Invoke-ConfirmYes $p1.Id $Afx 10000
    Det 'S1.dlg' ($d1.Dlg -ne [IntPtr]::Zero) ('#32770 with Yes(6): dlg=' + $d1.Dlg + ' yesClicked=' + $d1.YesClicked + ' gone=' + $d1.Gone + ' autoNoDialog=' + $d1.AutoNoDialog)
    if ($d1.Children -ne '') { Write-Host ('  [S1.dlg children] ' + $d1.Children) }
    if ($d1.Dlg -ne [IntPtr]::Zero) {
        if (-not $d1.Gone) { $ok1 = $false; $ev1 = 'confirm dialog refused to dismiss after two BM_CLICKs on Yes(6)' }
    } elseif ($d1.AutoNoDialog) {
        Write-Host '  [S1.dlg] ANOMALY: no #32770 confirm appeared but the file vanished - delete confirmations appear to be disabled on this machine'
    } else {
        $ok1 = $false; $ev1 = 'no #32770 confirm dialog within 10s and a.png still on disk'
    }
}
$aGone1 = $false
if ($ok1) {
    $aGone1 = Wait-FileState $Afx $false 10000
    Det 'S1.file' $aGone1 ('a.png gone from disk: ' + (-not (Test-Path $Afx)))
    if (-not $aGone1) { $ok1 = $false; $ev1 = 'a.png still on disk 10s after the delete' }
}
$t1 = ''
if ($ok1) {
    $t1 = Wait-TitleHas $main1 'b.png' 10000
    Det 'S1.title' $t1 ('title=[' + (Get-Title $main1) + ']')
    if (-not $t1) { $ok1 = $false; $ev1 = 'title never showed b.png (actual: [' + (Get-Title $main1) + '])' }
}
if ($ok1) {
    if ($aGone1) { $script:binOutstanding.Add('a.png') }
    $ev1 = 'a.png recycled (title=[' + (Get-Title $main1) + '])'
    if ($d1.AutoNoDialog) { $ev1 = 'ANOMALY no-confirm-dialog but ' + $ev1 }
}
Emit-S 'S1' $ok1 $ev1

# ---------------------------------------------------------------------------
# S2: WM_COMMAND 122 -> restore + re-insert + navigate. Then NavNext /
# NavPrev prove the position and order.
# ---------------------------------------------------------------------------
$ok2 = $ok1
$ev2 = ''
$aBack2 = $false
if ($ok2) {
    Post-Cmd $main1 122
    $aBack2 = Wait-Until { (Test-Path $Afx) -and ((Hash-Of $Afx) -eq $hA0) } 10000
    Det 'S2.file' $aBack2 ('a.png back, hash==' + $aBack2 + ' sha256=' + (Hash-Of $Afx))
    if (-not $aBack2) { $ok2 = $false; $ev2 = 'a.png not restored byte-identical within 10s (exists=' + (Test-Path $Afx) + ')' }
}
$t2a = $false
if ($ok2) {
    $t2a = Wait-TitleHas $main1 'a.png' 10000
    Det 'S2.title' $t2a ('title=[' + (Get-Title $main1) + ']')
    if (-not $t2a) { $ok2 = $false; $ev2 = 'title never returned to a.png (actual: [' + (Get-Title $main1) + '])' }
}
$n2a = $false; $n2b = $false
    if ($ok2) {
        if ($script:binOutstanding.Contains('a.png')) { [void]$script:binOutstanding.Remove('a.png') }
    Post-Cmd $main1 107   # NavNext
    $n2a = Wait-TitleHas $main1 'b.png' 10000
    Det 'S2.next' $n2a ('after NavNext title=[' + (Get-Title $main1) + ']')
    if (-not $n2a) { $ok2 = $false; $ev2 = 'NavNext after undo did not reach b.png (actual: [' + (Get-Title $main1) + '])' }
}
if ($ok2) {
    Post-Cmd $main1 108   # NavPrev
    $n2b = Wait-TitleHas $main1 'a.png' 10000
    Det 'S2.prev' $n2b ('after NavPrev title=[' + (Get-Title $main1) + ']')
    if (-not $n2b) { $ok2 = $false; $ev2 = 'NavPrev did not return to a.png (actual: [' + (Get-Title $main1) + '])' }
}
if ($ok2) { $ev2 = 'a.png restored byte-identical, order a->b->c intact (NavNext/NavPrev both landed)' }
Emit-S 'S2' $ok2 $ev2

# ---------------------------------------------------------------------------
# S3: WM_COMMAND 122 with the record consumed -> no-op.
# ---------------------------------------------------------------------------
$ok3 = $ok2
$ev3 = 'cascade: S2 red (a.png left in the recycle bin by the failed restore)'
if ($ok3) {
    Post-Cmd $main1 122
    Start-Sleep -Milliseconds 800
    $stillA = Wait-TitleLacks $main1 'b.png' 2000   # any flip to b/c = the no-op lied
    Det 'S3.title' $stillA ('title after consumed undo=[' + (Get-Title $main1) + ']')
    if (-not $stillA) { $ok3 = $false; $ev3 = 'second 122 changed the display (title=[' + (Get-Title $main1) + '])' }
}
$f3 = $false
if ($ok3) {
    $f3 = (Test-Path $Afx) -and ((Hash-Of $Afx) -eq $hA0) -and (Test-Path $Bfx) -and (Test-Path $Cfx)
    Det 'S3.files' $f3 ('a/b/c all on disk, a hash intact=' + ((Hash-Of $Afx) -eq $hA0))
    if (-not $f3) { $ok3 = $false; $ev3 = 'file state changed by a no-op undo' }
}
$alive3 = $false
if ($ok3) {
    $p1.Refresh()
    $alive3 = (-not $p1.HasExited)
    Det 'S3.alive' $alive3 ('process alive after consumed undo')
    if (-not $alive3) { $ok3 = $false; $ev3 = 'process died on a no-op undo' }
}
if ($ok3) { $ev3 = 'record consumed: no-op (title=[' + (Get-Title $main1) + '], files intact, alive)' }
Emit-S 'S3' $ok3 $ev3

# ---------------------------------------------------------------------------
# S4: NavNext x2 -> c.png; WM_COMMAND 14 + Yes -> permanent delete; 122 must
# NOT bring c.png back.
# ---------------------------------------------------------------------------
$ok4 = $ok3
$ev4 = 'cascade: prior scenario red (playlist state broken before the S4 nav)'
if ($ok4) {
    Post-Cmd $main1 107
    $n4a = Wait-TitleHas $main1 'b.png' 10000
    Det 'S4.nav1' $n4a ('after NavNext #1 title=[' + (Get-Title $main1) + ']')
    if (-not $n4a) { $ok4 = $false; $ev4 = 'NavNext #1 did not reach b.png (actual: [' + (Get-Title $main1) + '])' }
}
if ($ok4) {
    Post-Cmd $main1 107
    $n4b = Wait-TitleHas $main1 'c.png' 10000
    Det 'S4.nav2' $n4b ('after NavNext #2 title=[' + (Get-Title $main1) + ']')
    if (-not $n4b) { $ok4 = $false; $ev4 = 'NavNext #2 did not reach c.png (actual: [' + (Get-Title $main1) + '])' }
}
$d4 = $null
if ($ok4) {
    Post-Cmd $main1 14
    $d4 = Invoke-ConfirmYes $p1.Id $Cfx 10000
    Det 'S4.dlg' ($d4.Dlg -ne [IntPtr]::Zero) ('#32770 with Yes(6): dlg=' + $d4.Dlg + ' yesClicked=' + $d4.YesClicked + ' gone=' + $d4.Gone + ' autoNoDialog=' + $d4.AutoNoDialog)
    if ($d4.Children -ne '') { Write-Host ('  [S4.dlg children] ' + $d4.Children) }
    if ($d4.Dlg -ne [IntPtr]::Zero) {
        if (-not $d4.Gone) { $ok4 = $false; $ev4 = 'permanent-delete confirm dialog refused to dismiss after two BM_CLICKs on Yes(6)' }
    } elseif ($d4.AutoNoDialog) {
        Write-Host '  [S4.dlg] ANOMALY: no #32770 confirm appeared but c.png vanished - delete confirmations appear disabled on this machine'
    } else {
        $ok4 = $false; $ev4 = 'no #32770 confirm dialog within 10s and c.png still on disk'
    }
}
$cGone4 = $false
if ($ok4) {
    $cGone4 = Wait-FileState $Cfx $false 10000
    Det 'S4.file' $cGone4 ('c.png permanently gone: ' + (-not (Test-Path $Cfx)))
    if (-not $cGone4) { $ok4 = $false; $ev4 = 'c.png still on disk 10s after permanent delete' }
}
$t4 = $false
if ($ok4) {
    $t4 = (Wait-TitleHas $main1 'a.png' 10000) -and (Wait-TitleLacks $main1 'c.png' 1000)
    Det 'S4.title' $t4 ('title wrapped to=[' + (Get-Title $main1) + ']')
    if (-not $t4) { $ok4 = $false; $ev4 = 'title did not wrap to a.png after deleting c (actual: [' + (Get-Title $main1) + '])' }
}
if ($ok4) {
    Post-Cmd $main1 122
    Start-Sleep -Milliseconds 800
    $u4 = (-not (Test-Path $Cfx)) -and (Wait-TitleLacks $main1 'c.png' 1000)
    Det 'S4.undo' $u4 ('after 122: c exists=' + (Test-Path $Cfx) + ' title=[' + (Get-Title $main1) + ']')
    if (-not $u4) { $ok4 = $false; $ev4 = 'undo restored a PERMANENTLY deleted file (c.png exists=' + (Test-Path $Cfx) + ')' }
}
if ($ok4) { $ev4 = 'c.png permanently deleted (title=[' + (Get-Title $main1) + ']); 122 cannot bring it back' }
Emit-S 'S4' $ok4 $ev4

# ---------------------------------------------------------------------------
# S5: NavNext -> b.png; delete to bin + Yes; squatter b.png (different
# bytes) -> 122 refused; remove squatter -> 122 retry restores ORIGINAL.
# ---------------------------------------------------------------------------
$ok5 = $ok4
$ev5 = 'cascade: prior scenario red (matrix state broken before the S5 delete)'
if ($ok5) {
    Post-Cmd $main1 107
    $n5 = Wait-TitleHas $main1 'b.png' 10000
    Det 'S5.nav' $n5 ('after NavNext title=[' + (Get-Title $main1) + ']')
    if (-not $n5) { $ok5 = $false; $ev5 = 'NavNext did not reach b.png (actual: [' + (Get-Title $main1) + '])' }
}
$d5 = $null
$bGone5 = $false
if ($ok5) {
    Post-Cmd $main1 13
    $d5 = Invoke-ConfirmYes $p1.Id $Bfx 10000
    Det 'S5.dlg' ($d5.Dlg -ne [IntPtr]::Zero) ('#32770 with Yes(6): dlg=' + $d5.Dlg + ' yesClicked=' + $d5.YesClicked + ' gone=' + $d5.Gone + ' autoNoDialog=' + $d5.AutoNoDialog)
    if ($d5.Children -ne '') { Write-Host ('  [S5.dlg children] ' + $d5.Children) }
    if ($d5.Dlg -ne [IntPtr]::Zero) {
        if (-not $d5.Gone) { $ok5 = $false; $ev5 = 'confirm dialog refused to dismiss after two BM_CLICKs on Yes(6)' }
    } elseif (-not $d5.AutoNoDialog) {
        $ok5 = $false; $ev5 = 'no #32770 confirm dialog within 10s and b.png still on disk'
    }
}
if ($ok5) {
    $bGone5 = Wait-FileState $Bfx $false 10000
    Det 'S5.file' $bGone5 ('b.png recycled: ' + (-not (Test-Path $Bfx)))
    if (-not $bGone5) { $ok5 = $false; $ev5 = 'b.png still on disk 10s after the delete' }
}
$t5 = $false
if ($ok5) {
    if ($bGone5) { $script:binOutstanding.Add('b.png') }
    $t5 = Wait-TitleHas $main1 'a.png' 10000
    Det 'S5.title' $t5 ('title=[' + (Get-Title $main1) + ']')
    if (-not $t5) { $ok5 = $false; $ev5 = 'title did not fall back to a.png (actual: [' + (Get-Title $main1) + '])' }
}
$squatter5 = $false
$refused5 = $false
if ($ok5) {
    # The squatter: a VALID png with DIFFERENT bytes (magenta).
    [S178]::WritePng8($Bfx, 220, 30, 220)
    $hBNew = Hash-Of $Bfx
    Write-Host ('  [S5.squatter] new b.png sha256=' + $hBNew)
    Post-Cmd $main1 122
    Start-Sleep -Milliseconds 800
    $refused5 = ((Hash-Of $Bfx) -eq $hBNew) -and (Wait-TitleLacks $main1 'b.png' 2000)
    Det 'S5.refuse' $refused5 ('squatter intact=' + ((Hash-Of $Bfx) -eq $hBNew) + ' title=[' + (Get-Title $main1) + ']')
    if (-not $refused5) { $ok5 = $false; $ev5 = 'undo OVERWROTE the squatter or switched the display (title=[' + (Get-Title $main1) + '])' }
    if ($refused5) {
        # Remove the obstruction (never was in the bin - direct delete).
        Remove-Item $Bfx -Force
        Start-Sleep -Milliseconds 200
        Post-Cmd $main1 122   # the task-prescribed RETRY undo (record survives the refusal)
        $retry5 = Wait-Until { (Test-Path $Bfx) -and ((Hash-Of $Bfx) -eq $hB0) } 10000
        Det 'S5.retry' $retry5 ('retry restore: b.png sha256=' + (Hash-Of $Bfx))
        if (-not $retry5) { $ok5 = $false; $ev5 = 'retry undo did not restore the ORIGINAL b.png bytes (exists=' + (Test-Path $Bfx) + ')' }
        else {
            $tr5 = Wait-TitleHas $main1 'b.png' 10000
            Det 'S5.retrytitle' $tr5 ('title=[' + (Get-Title $main1) + ']')
            if (-not $tr5) { $ok5 = $false; $ev5 = 'retry undo restored bytes but the display stayed a.png (actual: [' + (Get-Title $main1) + '])' }
            else { if ($script:binOutstanding.Contains('b.png')) { [void]$script:binOutstanding.Remove('b.png') } }
        }
    }
}
if ($ok5) { $ev5 = 'refuse+retry both correct (squatter untouched, then ORIGINAL bytes back, title=[' + (Get-Title $main1) + '])' }
Emit-S 'S5' $ok5 $ev5

# Launch 1 teardown: WM_CLOSE, poll exit.
if ($main1 -ne [IntPtr]::Zero) { [void][S178]::PostMessage($main1, 0x0010, [IntPtr]::Zero, [IntPtr]::Zero) }
$code1 = Wait-Exit $p1 30000
if ($code1 -eq $null) {
    Write-Host ('  [launch1] did not exit within 30s, killing pid ' + $p1.Id)
    Stop-Process -Id $p1.Id -Force -ErrorAction SilentlyContinue
    $p1.WaitForExit(3000) | Out-Null
    $exitNote1 = 'FORCE-KILLED'
} else { $exitNote1 = 'exit=' + $code1 }
Write-Host ('  [launch1] closed: ' + $exitNote1)

# ===========================================================================
# LAUNCH 2 (direct-open arm): a.png only, playlist empty.
# Fixture isolation for the task's own premise: the playlist-less nav does a
# LIVE folder scan (src/window.rs nav_next -> Action::Scan, upstream viv.c-
# faithful), so any image left in fx\ by launch 1 would become the delete's
# nav target and the "blank display" expectation could never fire. Launch 2
# therefore runs with fx holding ONLY a.png. (Assertion text unchanged; this
# is fixture setup, not a product or assertion change.)
# ===========================================================================
Remove-Item $Bfx -Force -ErrorAction SilentlyContinue
Remove-Item $Cfx -Force -ErrorAction SilentlyContinue
$p2 = Start-Riv ('"' + $Afx + '"') 'launch2.err'
$main2 = Wait-Main $p2
$adopt2 = Wait-TitleHas $main2 'a.png' 15000
Start-Sleep -Milliseconds 800   # settle
$alive2 = (-not $p2.HasExited)
Write-Host ('  [launch2] pid=' + $p2.Id + ' main=' + $main2 + ' adopted=' + $adopt2 + ' title=[' + (Get-Title $main2) + ']')

# ---------------------------------------------------------------------------
# S6: WM_COMMAND 122 immediately after adopt -> no-op (nothing recorded).
# ---------------------------------------------------------------------------
$ok6 = $alive2 -and $adopt2
$ev6 = ''
if (-not $ok6) { $ev6 = 'launch2 adopt failed (cascade: a.png unrestored after the S2 red): alive=' + $alive2 + ' adopted=' + $adopt2 + ' title=[' + (Get-Title $main2) + ']' }
$t6a = ''
if ($ok6) {
    $t6a = Get-Title $main2
    Post-Cmd $main2 122
    Start-Sleep -Milliseconds 800
    $t6b = Get-Title $main2
    Det 'S6.title' ($t6a -eq $t6b) ('title before=[' + $t6a + '] after=[' + $t6b + ']')
    if ($t6a -ne $t6b) { $ok6 = $false; $ev6 = 'title changed on a record-less undo' }
}
if ($ok6) {
    $f6 = (Test-Path $Afx) -and ((Hash-Of $Afx) -eq $hA0)
    Det 'S6.file' $f6 ('a.png intact=' + $f6)
    if (-not $f6) { $ok6 = $false; $ev6 = 'a.png changed on a record-less undo' }
}
$alive6 = $false
if ($ok6) {
    $p2.Refresh()
    $alive6 = (-not $p2.HasExited)
    Det 'S6.alive' $alive6 ('process alive')
    if (-not $alive6) { $ok6 = $false; $ev6 = 'process died on a record-less undo' }
}
if ($ok6) { $ev6 = 'no-op at startup (title=[' + $t6b + '], file intact, alive)' }
Emit-S 'S6' $ok6 $ev6

# ---------------------------------------------------------------------------
# S7: graying gate. WM_INITMENU -> GetMenuState(122) MF_GRAYED; delete a
# (id 13 + Yes) -> blank title; WM_INITMENU -> 122 enabled; 122 restores.
# ---------------------------------------------------------------------------
$ok7 = $ok6
$ev7 = 'cascade: S6 red (no image adopted to exercise the graying ladder)'
$g1 = $false; $st1 = $u32max
if ($ok7) {
    $r1m = Wait-Menu122Grayed $main2 5000
    $g1 = $r1m.Ok; $st1 = $r1m.State
    Det 'S7.gray' $g1 ('GetMenuState(122)=0x' + $st1.ToString('X') + ' before any delete (MF_GRAYED=1)')
    if (-not $g1) { $ok7 = $false; $ev7 = 'id 122 not grayed with no undo record (state=0x' + $st1.ToString('X') + ')' }
}
$d7 = $null
$aGone7 = $false
if ($ok7) {
    Post-Cmd $main2 13
    $d7 = Invoke-ConfirmYes $p2.Id $Afx 10000
    Det 'S7.dlg' ($d7.Dlg -ne [IntPtr]::Zero) ('#32770 with Yes(6): dlg=' + $d7.Dlg + ' yesClicked=' + $d7.YesClicked + ' gone=' + $d7.Gone + ' autoNoDialog=' + $d7.AutoNoDialog)
    if ($d7.Children -ne '') { Write-Host ('  [S7.dlg children] ' + $d7.Children) }
    if ($d7.Dlg -ne [IntPtr]::Zero) {
        if (-not $d7.Gone) { $ok7 = $false; $ev7 = 'confirm dialog refused to dismiss after two BM_CLICKs on Yes(6)' }
    } elseif (-not $d7.AutoNoDialog) {
        $ok7 = $false; $ev7 = 'no #32770 confirm dialog within 10s and a.png still on disk'
    }
}
$t7a = $false
if ($ok7) {
    $aGone7 = Wait-FileState $Afx $false 10000
    Det 'S7.file' $aGone7 ('a.png recycled: ' + (-not (Test-Path $Afx)))
    if (-not $aGone7) { $ok7 = $false; $ev7 = 'a.png still on disk 10s after the delete' }
}
if ($ok7) {
    if ($aGone7) { $script:binOutstanding.Add('a.png') }
    # Blank display: the title drops the filename clause (app name only).
    $t7a = Wait-TitleLacks $main2 'a.png' 10000
    Det 'S7.blank' $t7a ('blanked title=[' + (Get-Title $main2) + ']')
    if (-not $t7a) { $ok7 = $false; $ev7 = 'title still shows a.png after deleting the only file (actual: [' + (Get-Title $main2) + '])' }
}
$g2 = $false; $st2 = $u32max
if ($ok7) {
    $r2m = Wait-Menu122Enabled $main2 5000
    $g2 = $r2m.Ok; $st2 = $r2m.State
    Det 'S7.enable' $g2 ('GetMenuState(122)=0x' + $st2.ToString('X') + ' after the delete (not grayed)')
    if (-not $g2) { $ok7 = $false; $ev7 = 'id 122 still grayed WITH an undo record standing (state=0x' + $st2.ToString('X') + ')' }
}
if ($ok7) {
    Post-Cmd $main2 122
    $r7 = Wait-Until { (Test-Path $Afx) -and ((Hash-Of $Afx) -eq $hA0) } 10000
    Det 'S7.restore' $r7 ('a.png sha256=' + (Hash-Of $Afx))
    if (-not $r7) { $ok7 = $false; $ev7 = 'direct-open undo did not restore a.png byte-identical (exists=' + (Test-Path $Afx) + ')' }
    else {
        $tr7 = Wait-TitleHas $main2 'a.png' 10000
        Det 'S7.title' $tr7 ('title=[' + (Get-Title $main2) + ']')
        if (-not $tr7) { $ok7 = $false; $ev7 = 'undo restored the file but the title stayed blank (actual: [' + (Get-Title $main2) + '])' }
        else { if ($script:binOutstanding.Contains('a.png')) { [void]$script:binOutstanding.Remove('a.png') } }
    }
}
if ($ok7) { $ev7 = 'grayed->delete->blank title->enabled->restored (title=[' + (Get-Title $main2) + '], grayState=0x' + $st1.ToString('X') + '->0x' + $st2.ToString('X') + ')' }
Emit-S 'S7' $ok7 $ev7

# Launch 2 teardown.
if ($main2 -ne [IntPtr]::Zero) { [void][S178]::PostMessage($main2, 0x0010, [IntPtr]::Zero, [IntPtr]::Zero) }
$code2 = Wait-Exit $p2 30000
if ($code2 -eq $null) {
    Write-Host ('  [launch2] did not exit within 30s, killing pid ' + $p2.Id)
    Stop-Process -Id $p2.Id -Force -ErrorAction SilentlyContinue
    $p2.WaitForExit(3000) | Out-Null
    $exitNote2 = 'FORCE-KILLED'
} else { $exitNote2 = 'exit=' + $code2 }
Write-Host ('  [launch2] closed: ' + $exitNote2)

} catch {
    Write-Output ('ERROR: unexpected exception mid-matrix: ' + $_.Exception.Message)
    Write-Output $_.ScriptStackTrace
    # Path-targeted cleanup of OUR launches only.
    foreach ($pp in @($p1, $p2)) {
        if (($pp -ne $null) -and (-not $pp.HasExited)) {
            Write-Host ('killing our pid ' + $pp.Id)
            Stop-Process -Id $pp.Id -Force -ErrorAction SilentlyContinue
        }
    }
    if (Test-Path $Ini) { Remove-Item $Ini -Force -ErrorAction SilentlyContinue }
    Write-Output ('FIXTURE STATE at abort: a=' + (Test-Path $Afx) + ' b=' + (Test-Path $Bfx) + ' c=' + (Test-Path $Cfx))
    if ($script:binOutstanding.Count -gt 0) {
        Write-Output ('RECYCLE BIN RESIDUE possible for: ' + (($script:binOutstanding) -join ', ') + ' (not cleaned; the bin was never emptied)')
    }
    $script:fail = $script:fail + 1
    Write-Output ('SMOKE178: ' + $script:pass + '/' + ($script:total + 1))
    Stop-Log
    exit 1
}

# ---------------------------------------------------------------------------
# Teardown: the ini generated by THIS RUN (the gate guaranteed it was absent
# at start) is deleted; no riviv left behind; stderr dumps on failure.
# ---------------------------------------------------------------------------
$iniRemoved = $true
if (Test-Path $Ini) {
    Remove-Item $Ini -Force -ErrorAction SilentlyContinue
    $iniRemoved = -not (Test-Path $Ini)
}
Det 'teardown.ini' $iniRemoved ('this-run ini removed from target\release: ' + $iniRemoved)
$leftover = @(Get-Process riviv -ErrorAction SilentlyContinue)
Det 'teardown.procs' ($leftover.Count -eq 0) ('riviv processes left: ' + (($leftover | ForEach-Object { $_.Id }) -join ','))

if ($script:binOutstanding.Count -gt 0) {
    Write-Output ('NOTE: fixture residue possibly in the recycle bin: ' + (($script:binOutstanding) -join ', ') + ' (the bin was never emptied; restore manually if unwanted)')
}

if ($script:fail -gt 0) {
    Write-Output 'FAILURES: per-launch stderr follows.'
    foreach ($e in @(@('launch1', (Join-Path $Stage 'launch1.err')), @('launch2', (Join-Path $Stage 'launch2.err')))) {
        $body = ''
        if (Test-Path $e[1]) {
            try {
                $fs = [IO.File]::Open($e[1], [IO.FileMode]::Open, [IO.FileAccess]::Read, [IO.FileShare]::ReadWrite)
                try { $sr = New-Object IO.StreamReader($fs); $body = $sr.ReadToEnd() } finally { $fs.Dispose() }
            } catch { $body = '(stderr unreadable)' }
        }
        if ($body -ne '') {
            Write-Output ('--- ' + $e[0] + ' stderr ---')
            Write-Output $body
        }
    }
}

Write-Output ('SMOKE178: ' + $script:pass + '/' + $script:total)
Stop-Log
if ($script:fail -gt 0) { exit 1 }
exit 0
